name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: remove the need to build the API module first.
      # Ideally it should be possible to just build the parent project and the API module should be built automatically.
      # See https://github.com/krzema12/kotlin-rpc/issues/7
      - run: ./gradlew :api:build
      - run: ./gradlew build
